// Code generated by protoc-gen-go. DO NOT EDIT.
// source: employee.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Employee struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string               `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string               `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Password             string               `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Phone                string               `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Roles                []*Role              `protobuf:"bytes,6,rep,name=roles,proto3" json:"roles,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Employee) Reset()         { *m = Employee{} }
func (m *Employee) String() string { return proto.CompactTextString(m) }
func (*Employee) ProtoMessage()    {}
func (*Employee) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb50a19aa79a6eac, []int{0}
}

func (m *Employee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Employee.Unmarshal(m, b)
}
func (m *Employee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Employee.Marshal(b, m, deterministic)
}
func (m *Employee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Employee.Merge(m, src)
}
func (m *Employee) XXX_Size() int {
	return xxx_messageInfo_Employee.Size(m)
}
func (m *Employee) XXX_DiscardUnknown() {
	xxx_messageInfo_Employee.DiscardUnknown(m)
}

var xxx_messageInfo_Employee proto.InternalMessageInfo

func (m *Employee) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Employee) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Employee) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Employee) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Employee) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Employee) GetRoles() []*Role {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *Employee) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Employee) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type EmployeeFilter struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmployeeFilter) Reset()         { *m = EmployeeFilter{} }
func (m *EmployeeFilter) String() string { return proto.CompactTextString(m) }
func (*EmployeeFilter) ProtoMessage()    {}
func (*EmployeeFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb50a19aa79a6eac, []int{1}
}

func (m *EmployeeFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmployeeFilter.Unmarshal(m, b)
}
func (m *EmployeeFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmployeeFilter.Marshal(b, m, deterministic)
}
func (m *EmployeeFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmployeeFilter.Merge(m, src)
}
func (m *EmployeeFilter) XXX_Size() int {
	return xxx_messageInfo_EmployeeFilter.Size(m)
}
func (m *EmployeeFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_EmployeeFilter.DiscardUnknown(m)
}

var xxx_messageInfo_EmployeeFilter proto.InternalMessageInfo

func (m *EmployeeFilter) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EmployeeFilter) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type NewEmployeeRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Roles                []*Role  `protobuf:"bytes,5,rep,name=roles,proto3" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewEmployeeRequest) Reset()         { *m = NewEmployeeRequest{} }
func (m *NewEmployeeRequest) String() string { return proto.CompactTextString(m) }
func (*NewEmployeeRequest) ProtoMessage()    {}
func (*NewEmployeeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb50a19aa79a6eac, []int{2}
}

func (m *NewEmployeeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewEmployeeRequest.Unmarshal(m, b)
}
func (m *NewEmployeeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewEmployeeRequest.Marshal(b, m, deterministic)
}
func (m *NewEmployeeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewEmployeeRequest.Merge(m, src)
}
func (m *NewEmployeeRequest) XXX_Size() int {
	return xxx_messageInfo_NewEmployeeRequest.Size(m)
}
func (m *NewEmployeeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewEmployeeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewEmployeeRequest proto.InternalMessageInfo

func (m *NewEmployeeRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *NewEmployeeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NewEmployeeRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *NewEmployeeRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *NewEmployeeRequest) GetRoles() []*Role {
	if m != nil {
		return m.Roles
	}
	return nil
}

type UpdateEmployeeRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Phone                string   `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Roles                []*Role  `protobuf:"bytes,6,rep,name=roles,proto3" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateEmployeeRequest) Reset()         { *m = UpdateEmployeeRequest{} }
func (m *UpdateEmployeeRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateEmployeeRequest) ProtoMessage()    {}
func (*UpdateEmployeeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb50a19aa79a6eac, []int{3}
}

func (m *UpdateEmployeeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateEmployeeRequest.Unmarshal(m, b)
}
func (m *UpdateEmployeeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateEmployeeRequest.Marshal(b, m, deterministic)
}
func (m *UpdateEmployeeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateEmployeeRequest.Merge(m, src)
}
func (m *UpdateEmployeeRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateEmployeeRequest.Size(m)
}
func (m *UpdateEmployeeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateEmployeeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateEmployeeRequest proto.InternalMessageInfo

func (m *UpdateEmployeeRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateEmployeeRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpdateEmployeeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateEmployeeRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UpdateEmployeeRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UpdateEmployeeRequest) GetRoles() []*Role {
	if m != nil {
		return m.Roles
	}
	return nil
}

func init() {
	proto.RegisterType((*Employee)(nil), "pb.Employee")
	proto.RegisterType((*EmployeeFilter)(nil), "pb.EmployeeFilter")
	proto.RegisterType((*NewEmployeeRequest)(nil), "pb.NewEmployeeRequest")
	proto.RegisterType((*UpdateEmployeeRequest)(nil), "pb.UpdateEmployeeRequest")
}

func init() { proto.RegisterFile("employee.proto", fileDescriptor_eb50a19aa79a6eac) }

var fileDescriptor_eb50a19aa79a6eac = []byte{
	// 408 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x93, 0x41, 0x6f, 0x9b, 0x30,
	0x14, 0xc7, 0x03, 0x09, 0x19, 0x79, 0x4c, 0x4c, 0xb2, 0xb6, 0x88, 0xb1, 0x69, 0x8b, 0x38, 0xe5,
	0x44, 0xb4, 0x4c, 0x9b, 0x34, 0x4d, 0x9a, 0x14, 0x69, 0xd9, 0x6e, 0x3d, 0xd0, 0xf6, 0x5c, 0x99,
	0xf0, 0x9a, 0x5a, 0x02, 0xec, 0x82, 0xd3, 0x28, 0xdf, 0xa1, 0x87, 0x7e, 0x87, 0x7e, 0xc9, 0x1e,
	0x2b, 0x0c, 0xa4, 0x49, 0x20, 0x6a, 0x8f, 0xbd, 0xe1, 0xbf, 0xff, 0x7f, 0xfb, 0xbd, 0xdf, 0x33,
	0x60, 0x63, 0x22, 0x62, 0xbe, 0x41, 0xf4, 0x45, 0xc6, 0x25, 0x27, 0xba, 0x08, 0xdd, 0xaf, 0x4b,
	0xce, 0x97, 0x31, 0x4e, 0x94, 0x12, 0xae, 0x2e, 0x27, 0x92, 0x25, 0x98, 0x4b, 0x9a, 0x88, 0xd2,
	0xe4, 0x7e, 0xae, 0x0c, 0x54, 0xb0, 0x09, 0x4d, 0x53, 0x2e, 0xa9, 0x64, 0x3c, 0xcd, 0xab, 0xdd,
	0x4f, 0x87, 0x71, 0x4c, 0x84, 0xdc, 0x54, 0x9b, 0x90, 0xf1, 0xb8, 0xba, 0xcb, 0xbb, 0xd5, 0xc1,
	0x9c, 0x57, 0xd7, 0x13, 0x1b, 0x74, 0x16, 0x39, 0xda, 0x48, 0x1b, 0x0f, 0x02, 0x9d, 0x45, 0xe4,
	0x3d, 0x18, 0x98, 0x50, 0x16, 0x3b, 0xba, 0x92, 0xca, 0x05, 0x21, 0xd0, 0x4b, 0x69, 0x82, 0x4e,
	0x57, 0x89, 0xea, 0x9b, 0xb8, 0x60, 0x0a, 0x9a, 0xe7, 0x6b, 0x9e, 0x45, 0x4e, 0x4f, 0xe9, 0xdb,
	0x75, 0x71, 0x8a, 0xb8, 0xe2, 0x29, 0x3a, 0x46, 0x79, 0x8a, 0x5a, 0x90, 0x2f, 0x60, 0x14, 0x65,
	0xe4, 0x4e, 0x7f, 0xd4, 0x1d, 0x5b, 0x53, 0xd3, 0x17, 0xa1, 0x1f, 0xf0, 0x18, 0x83, 0x52, 0x26,
	0xbf, 0x00, 0x16, 0x19, 0x52, 0x89, 0xd1, 0x05, 0x95, 0xce, 0x9b, 0x91, 0x36, 0xb6, 0xa6, 0xae,
	0x5f, 0xb6, 0xe5, 0xd7, 0x6d, 0xf9, 0x67, 0x35, 0x95, 0x60, 0x50, 0xb9, 0x67, 0xb2, 0x88, 0xae,
	0x44, 0x54, 0x47, 0xcd, 0xe7, 0xa3, 0x95, 0x7b, 0x26, 0xbd, 0x9f, 0x60, 0xd7, 0x34, 0xfe, 0xb1,
	0x58, 0x62, 0xf6, 0x32, 0x26, 0xde, 0x9d, 0x06, 0xe4, 0x04, 0xd7, 0x75, 0x36, 0xc0, 0xeb, 0x15,
	0xe6, 0xf2, 0xc9, 0xac, 0xb5, 0x01, 0xd4, 0x8f, 0x00, 0xec, 0x1e, 0x03, 0xd8, 0x6b, 0x05, 0x68,
	0xb4, 0x02, 0xf4, 0xee, 0x35, 0xf8, 0x70, 0xae, 0x1a, 0x3b, 0xac, 0xea, 0x15, 0x8d, 0x79, 0xfa,
	0xa0, 0xc1, 0xbb, 0xba, 0xbe, 0x53, 0xcc, 0x6e, 0xd8, 0x02, 0xc9, 0x37, 0xb0, 0xfe, 0xa3, 0xdc,
	0xbe, 0x4a, 0x52, 0x64, 0xf6, 0xa7, 0xe2, 0xbe, 0xdd, 0xd5, 0xbc, 0x0e, 0xf9, 0x01, 0xd6, 0x0e,
	0x7e, 0x32, 0x2c, 0xb6, 0x9b, 0xf3, 0x68, 0xc4, 0x7e, 0x83, 0xbd, 0x8f, 0x88, 0x7c, 0x2c, 0x1c,
	0xad, 0xd8, 0x1a, 0xe1, 0x3f, 0x60, 0xff, 0xc5, 0x18, 0x77, 0xc2, 0x6d, 0x95, 0x0e, 0x1b, 0x0f,
	0x6f, 0x5e, 0xfc, 0x8a, 0x5e, 0x27, 0xec, 0x2b, 0xe5, 0xfb, 0x63, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x15, 0x63, 0x60, 0x8f, 0xff, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EmployeeServiceClient is the client API for EmployeeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EmployeeServiceClient interface {
	GetEmployee(ctx context.Context, in *EmployeeFilter, opts ...grpc.CallOption) (*Employee, error)
	NewEmployee(ctx context.Context, in *NewEmployeeRequest, opts ...grpc.CallOption) (*Employee, error)
	UpdateEmployee(ctx context.Context, in *UpdateEmployeeRequest, opts ...grpc.CallOption) (*Employee, error)
	DeleteEmployee(ctx context.Context, in *EmployeeFilter, opts ...grpc.CallOption) (*empty.Empty, error)
}

type employeeServiceClient struct {
	cc *grpc.ClientConn
}

func NewEmployeeServiceClient(cc *grpc.ClientConn) EmployeeServiceClient {
	return &employeeServiceClient{cc}
}

func (c *employeeServiceClient) GetEmployee(ctx context.Context, in *EmployeeFilter, opts ...grpc.CallOption) (*Employee, error) {
	out := new(Employee)
	err := c.cc.Invoke(ctx, "/pb.EmployeeService/GetEmployee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeServiceClient) NewEmployee(ctx context.Context, in *NewEmployeeRequest, opts ...grpc.CallOption) (*Employee, error) {
	out := new(Employee)
	err := c.cc.Invoke(ctx, "/pb.EmployeeService/NewEmployee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeServiceClient) UpdateEmployee(ctx context.Context, in *UpdateEmployeeRequest, opts ...grpc.CallOption) (*Employee, error) {
	out := new(Employee)
	err := c.cc.Invoke(ctx, "/pb.EmployeeService/UpdateEmployee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeServiceClient) DeleteEmployee(ctx context.Context, in *EmployeeFilter, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pb.EmployeeService/DeleteEmployee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmployeeServiceServer is the server API for EmployeeService service.
type EmployeeServiceServer interface {
	GetEmployee(context.Context, *EmployeeFilter) (*Employee, error)
	NewEmployee(context.Context, *NewEmployeeRequest) (*Employee, error)
	UpdateEmployee(context.Context, *UpdateEmployeeRequest) (*Employee, error)
	DeleteEmployee(context.Context, *EmployeeFilter) (*empty.Empty, error)
}

// UnimplementedEmployeeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedEmployeeServiceServer struct {
}

func (*UnimplementedEmployeeServiceServer) GetEmployee(ctx context.Context, req *EmployeeFilter) (*Employee, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEmployee not implemented")
}
func (*UnimplementedEmployeeServiceServer) NewEmployee(ctx context.Context, req *NewEmployeeRequest) (*Employee, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewEmployee not implemented")
}
func (*UnimplementedEmployeeServiceServer) UpdateEmployee(ctx context.Context, req *UpdateEmployeeRequest) (*Employee, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEmployee not implemented")
}
func (*UnimplementedEmployeeServiceServer) DeleteEmployee(ctx context.Context, req *EmployeeFilter) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEmployee not implemented")
}

func RegisterEmployeeServiceServer(s *grpc.Server, srv EmployeeServiceServer) {
	s.RegisterService(&_EmployeeService_serviceDesc, srv)
}

func _EmployeeService_GetEmployee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmployeeFilter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServiceServer).GetEmployee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.EmployeeService/GetEmployee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServiceServer).GetEmployee(ctx, req.(*EmployeeFilter))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeService_NewEmployee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewEmployeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServiceServer).NewEmployee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.EmployeeService/NewEmployee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServiceServer).NewEmployee(ctx, req.(*NewEmployeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeService_UpdateEmployee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEmployeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServiceServer).UpdateEmployee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.EmployeeService/UpdateEmployee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServiceServer).UpdateEmployee(ctx, req.(*UpdateEmployeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeService_DeleteEmployee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmployeeFilter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServiceServer).DeleteEmployee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.EmployeeService/DeleteEmployee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServiceServer).DeleteEmployee(ctx, req.(*EmployeeFilter))
	}
	return interceptor(ctx, in, info, handler)
}

var _EmployeeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.EmployeeService",
	HandlerType: (*EmployeeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEmployee",
			Handler:    _EmployeeService_GetEmployee_Handler,
		},
		{
			MethodName: "NewEmployee",
			Handler:    _EmployeeService_NewEmployee_Handler,
		},
		{
			MethodName: "UpdateEmployee",
			Handler:    _EmployeeService_UpdateEmployee_Handler,
		},
		{
			MethodName: "DeleteEmployee",
			Handler:    _EmployeeService_DeleteEmployee_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "employee.proto",
}
