// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event struct {
	EventId       string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Channel       string `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	Type          string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	AggregateId   string `protobuf:"bytes,4,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	AggregateType string `protobuf:"bytes,5,opt,name=aggregate_type,json=aggregateType,proto3" json:"aggregate_type,omitempty"`
	// Types that are valid to be assigned to Data:
	//	*Event_Employee
	//	*Event_UpdateRequest
	//	*Event_EmployeeFilter
	Data                 isEvent_Data         `protobuf_oneof:"data"`
	Originator           *Event_Claims        `protobuf:"bytes,9,opt,name=originator,proto3" json:"originator,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetEventId() string {
	if m != nil {
		return m.EventId
	}
	return ""
}

func (m *Event) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *Event) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Event) GetAggregateId() string {
	if m != nil {
		return m.AggregateId
	}
	return ""
}

func (m *Event) GetAggregateType() string {
	if m != nil {
		return m.AggregateType
	}
	return ""
}

type isEvent_Data interface {
	isEvent_Data()
}

type Event_Employee struct {
	Employee *Employee `protobuf:"bytes,6,opt,name=employee,proto3,oneof"`
}

type Event_UpdateRequest struct {
	UpdateRequest *UpdateEmployeeRequest `protobuf:"bytes,7,opt,name=update_request,json=updateRequest,proto3,oneof"`
}

type Event_EmployeeFilter struct {
	EmployeeFilter *EmployeeFilter `protobuf:"bytes,8,opt,name=employee_filter,json=employeeFilter,proto3,oneof"`
}

func (*Event_Employee) isEvent_Data() {}

func (*Event_UpdateRequest) isEvent_Data() {}

func (*Event_EmployeeFilter) isEvent_Data() {}

func (m *Event) GetData() isEvent_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Event) GetEmployee() *Employee {
	if x, ok := m.GetData().(*Event_Employee); ok {
		return x.Employee
	}
	return nil
}

func (m *Event) GetUpdateRequest() *UpdateEmployeeRequest {
	if x, ok := m.GetData().(*Event_UpdateRequest); ok {
		return x.UpdateRequest
	}
	return nil
}

func (m *Event) GetEmployeeFilter() *EmployeeFilter {
	if x, ok := m.GetData().(*Event_EmployeeFilter); ok {
		return x.EmployeeFilter
	}
	return nil
}

func (m *Event) GetOriginator() *Event_Claims {
	if m != nil {
		return m.Originator
	}
	return nil
}

func (m *Event) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Event) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Event_Employee)(nil),
		(*Event_UpdateRequest)(nil),
		(*Event_EmployeeFilter)(nil),
	}
}

type Event_Claims struct {
	EntityId             string   `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Entity               string   `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"`
	Login                string   `protobuf:"bytes,3,opt,name=login,proto3" json:"login,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event_Claims) Reset()         { *m = Event_Claims{} }
func (m *Event_Claims) String() string { return proto.CompactTextString(m) }
func (*Event_Claims) ProtoMessage()    {}
func (*Event_Claims) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{0, 0}
}

func (m *Event_Claims) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event_Claims.Unmarshal(m, b)
}
func (m *Event_Claims) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event_Claims.Marshal(b, m, deterministic)
}
func (m *Event_Claims) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event_Claims.Merge(m, src)
}
func (m *Event_Claims) XXX_Size() int {
	return xxx_messageInfo_Event_Claims.Size(m)
}
func (m *Event_Claims) XXX_DiscardUnknown() {
	xxx_messageInfo_Event_Claims.DiscardUnknown(m)
}

var xxx_messageInfo_Event_Claims proto.InternalMessageInfo

func (m *Event_Claims) GetEntityId() string {
	if m != nil {
		return m.EntityId
	}
	return ""
}

func (m *Event_Claims) GetEntity() string {
	if m != nil {
		return m.Entity
	}
	return ""
}

func (m *Event_Claims) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func init() {
	proto.RegisterType((*Event)(nil), "pb.Event")
	proto.RegisterType((*Event_Claims)(nil), "pb.Event.Claims")
}

func init() { proto.RegisterFile("event.proto", fileDescriptor_2d17a9d3f0ddf27e) }

var fileDescriptor_2d17a9d3f0ddf27e = []byte{
	// 363 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x51, 0xcd, 0x4e, 0xea, 0x40,
	0x14, 0x06, 0x6e, 0x29, 0xed, 0xe1, 0xe7, 0xde, 0x4c, 0x6e, 0xcc, 0x50, 0x17, 0xa2, 0x89, 0x09,
	0x71, 0x51, 0x8c, 0xae, 0x5c, 0xb8, 0x10, 0x83, 0x81, 0x6d, 0xc5, 0x35, 0x99, 0xd2, 0x43, 0x9d,
	0xa4, 0xed, 0xd4, 0x32, 0x98, 0xf0, 0x1c, 0xbe, 0xb0, 0xe9, 0x99, 0xb6, 0xb0, 0x9b, 0xef, 0xf7,
	0x34, 0xfd, 0xa0, 0x8f, 0xdf, 0x98, 0x69, 0x3f, 0x2f, 0x94, 0x56, 0xac, 0x93, 0x87, 0xde, 0x55,
	0xac, 0x54, 0x9c, 0xe0, 0x8c, 0x98, 0xf0, 0xb0, 0x9b, 0x69, 0x99, 0xe2, 0x5e, 0x8b, 0x34, 0x37,
	0x26, 0x6f, 0x84, 0x69, 0x9e, 0xa8, 0x23, 0xa2, 0xc1, 0x37, 0x3f, 0x16, 0x74, 0x17, 0x65, 0x09,
	0x1b, 0x83, 0x43, 0x6d, 0x1b, 0x19, 0xf1, 0xf6, 0xa4, 0x3d, 0x75, 0x83, 0x1e, 0xe1, 0x55, 0xc4,
	0x38, 0xf4, 0xb6, 0x9f, 0x22, 0xcb, 0x30, 0xe1, 0x1d, 0xa3, 0x54, 0x90, 0x31, 0xb0, 0xf4, 0x31,
	0x47, 0xfe, 0x87, 0x68, 0x7a, 0xb3, 0x6b, 0x18, 0x88, 0x38, 0x2e, 0x30, 0x16, 0x1a, 0xcb, 0x32,
	0x8b, 0xb4, 0x7e, 0xc3, 0xad, 0x22, 0x76, 0x0b, 0xa3, 0x93, 0x85, 0x0a, 0xba, 0x64, 0x1a, 0x36,
	0xec, 0xba, 0x6c, 0xba, 0x03, 0xa7, 0xfe, 0x5c, 0x6e, 0x4f, 0xda, 0xd3, 0xfe, 0xc3, 0xc0, 0xcf,
	0x43, 0x7f, 0x51, 0x71, 0xcb, 0x56, 0xd0, 0xe8, 0x6c, 0x0e, 0xa3, 0x43, 0x1e, 0x95, 0x7d, 0x05,
	0x7e, 0x1d, 0x70, 0xaf, 0x79, 0x8f, 0x12, 0xe3, 0x32, 0xf1, 0x41, 0x4a, 0x9d, 0x0b, 0x8c, 0x61,
	0xd9, 0x0a, 0x86, 0x26, 0x52, 0x11, 0xec, 0x19, 0xfe, 0xd6, 0x7d, 0x9b, 0x9d, 0x4c, 0x34, 0x16,
	0xdc, 0xa1, 0x12, 0x76, 0x7e, 0xf6, 0x8d, 0x94, 0x65, 0x2b, 0x68, 0xfe, 0xa5, 0x61, 0xd8, 0x3d,
	0x80, 0x2a, 0x64, 0x2c, 0x33, 0xa1, 0x55, 0xc1, 0x5d, 0x4a, 0xfe, 0xa3, 0x24, 0xad, 0xf4, 0x9a,
	0x08, 0x99, 0xee, 0x83, 0x33, 0x0f, 0x7b, 0x02, 0xd8, 0x16, 0x28, 0x34, 0x46, 0x1b, 0xa1, 0x39,
	0x50, 0xc2, 0xf3, 0xcd, 0x86, 0x7e, 0xbd, 0xa1, 0xbf, 0xae, 0x37, 0x0c, 0xdc, 0xca, 0xfd, 0xa2,
	0xbd, 0x77, 0xb0, 0x4d, 0x21, 0xbb, 0x04, 0x17, 0x33, 0x2d, 0xf5, 0xf1, 0xb4, 0x9c, 0x63, 0x88,
	0x55, 0xc4, 0x2e, 0xc0, 0x36, 0xef, 0x6a, 0xb9, 0x0a, 0xb1, 0xff, 0xd0, 0x4d, 0x54, 0x2c, 0xb3,
	0x6a, 0x39, 0x03, 0xe6, 0x36, 0x58, 0x91, 0xd0, 0x22, 0xb4, 0xe9, 0xf6, 0xe3, 0x6f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xfe, 0xb8, 0x5c, 0xd7, 0x60, 0x02, 0x00, 0x00,
}
